spring:
  application:
    name: demoConfigServer
  cloud:
    config:
      server:
        git:
          uri: <Git URL>
          default-label: main
          force-pull: true
          clone-on-start: true
          basedir: <URL>  # 클론될 위치 지정
          search-paths: /*

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: refresh,health

logging:
  level:
    org.springframework.cloud: DEBUG